name: iron-deprivation-r
channels:
  - conda-forge
dependencies:
  - r-base=4.2
  - r-tidyverse
  - r-readxl
  - r-openxlsx
  - r-ggplot2
  - r-pheatmap
  - r-optparse
  - r-data.table
  - r-rcolorbrewer
  - r-patchwork
  - make
